version: '3.1'
services:
  db:
    image: mysql
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cerbasi
      MYSQL_USER: ${DB_USERNAME:cerbasi}
      MYSQL_PASSWORD: ${DB_PASSWORD:root}
    ports:
      - '3308:3306'